# Generated by Django 6.0.7 on 2026-08-18 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_household_householdmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('brand', models.CharField(blank=True, max_length=100)),
                ('unit_type', models.CharField(choices=[('weight', 'Weight (kg)'), ('count', 'Count (items)')], max_length=10)),
                ('typical_package_size', models.DecimalField(decimal_places=2, max_digits=8)),
                ('typical_price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_products', to='accounts.household')),
            ],
        ),
        migrations.CreateModel(
            name='FoodBag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatity_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price_paid', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bags', to='food.foodproduct')),
            ],
        ),
    ]
