# Generated by Django 6.0.7 on 2026-08-18 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodbag',
            old_name='quatity_total',
            new_name='quantity_total',
        ),
    ]
