# Generated by Django 6.0.7 on 2026-08-18 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_rename_quatity_total_foodbag_quantity_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbag',
            name='purchase_date',
            field=models.DateField(default='2026-08-18'),
            preserve_default=False,
        ),
    ]
