# Generated by Django 6.0.7 on 2026-08-18 18:27

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_foodbag_purchase_date'),
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=50)),
                ('portion_amount', models.DecimalField(decimal_places=2, max_digits=8)),
                ('days_of_week', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=3))),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_slots', to='pets.pet')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feeding_slots', to='food.foodproduct')),
            ],
            options={
                'ordering': ['pet', 'start_date'],
            },
        ),
        migrations.CreateModel(
            name='MissedMeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feeding_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='missed_meals', to='food.feedingslot')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('feeding_slot', 'date')},
            },
        ),
    ]
