# Generated by Django 6.0.7 on 2026-08-18 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0004_feedingslot_missedmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodbag',
            name='finished_early_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
